### ISSUE TITLE
IPositionProvider.UpdatePositionRequested event doesn't do what I expect

### ISSUE THREAD

**Issue by Lakritzator** [raflop/ToastNotifications#31]
I am trying to make a SystemTrayPositionProvider (implementation of IPositionProvider) which follows the system tray when it's moved.

I got quite far: I get the right information and I **could** supply the "correct" coordinates.

But I noticed that when I handle the movement of the task bar and call the UpdatePositionRequested event, GetPosition is called but EjectDirection and also GetHeight are not queried. The toast itself doesn't move, but window where it's contained (??) does... this makes the toast stay **near** it's original location.

This causes issues when the task bar moves from one screen to another, or moved from bottom to top.

Maybe I have my expectations wrong, or I missed something, so I hope you can give me some tips.

**Comment by Lakritzator** [comment]
Example code: https://github.com/dapplo/Dapplo.CaliburnMicro/blob/master/src/Dapplo.CaliburnMicro.Toasts/SystemTrayPositionProvider.cs

**Comment by Lakritzator** [comment]
Oh yes, forgot to say... The actualPopupHeight seem to be the height of the screen, which was returned by GetHeight. This might actually be preventing me to calculate the correct location.

I implemented GetHeight by looking at https://github.com/raflop/ToastNotifications/blob/master-v2/Src/ToastNotifications/Position/PrimaryScreenPositionProvider.cs

**Comment by Lakritzator** [comment]
There is no main window, there is only a context menu from which everything is controlled. It is a MVVM composition (dependency injection with addons) based framework which Greenshot will used. I didn't expect you to check out the code :smile: 

Thanks, I wild test the change tomorrow.

If GetHeight isn't called, what should I do with resolution change, dispose the notified and recreate it?

**Comment by Lakritzator** [comment]
Although I was somewhat sceptical about this change, as I wasn't sure it was only the EjectDirection which caused the issues, your change works VERY well. The Toasts now move to the location of the taskbar after dragging it. The only thing that might be an issue, is the GetHeight, as moving the taskbar to a different screen will probably cause issues.

When can you update the NuGet package?

P.S.
My implementation wraps your library with MVVM functionality, using CaliburnMicro, but as this somehow doesn't 100% feel natural I might create a different issue for that. At least to describe to you and others how it can be used, maybe you can improve on it.

**Comment by raflop** [comment]
Hi, I'm glad it works for you :)
I will add possibility to refresh height as you mentioned, then I will publish fix as a nuget package, I think it will be possible on todays night :)

**Comment by Lakritzator** [comment]
P.S.
I would contribute the SystemTrayPositionProvider, but it depends heavily on some other code I wrote and use for the sake of maintainability.

It's not very hard to build yourself, but it is a bit of work:

Look at my implementation of the [IPositionProvider](https://github.com/raflop/ToastNotifications/blob/master-v2/Src/ToastNotifications/Position/PrimaryScreenPositionProvider.cs) for the "base" of your version.

To get the location ([AppBarEdges](https://github.com/dapplo/Dapplo.Windows/blob/master/src/Dapplo.Windows.Shell32/Enums/AppBarEdges.cs)) and bounds ([RECT](https://github.com/dapplo/Dapplo.Windows/blob/master/src/Dapplo.Windows.Common/Structs/RECT.cs)) of the taskbar you will need to call SHAppBarMessage from the shell32.dll with [ABM_GETTASKBARPOS](https://github.com/dapplo/Dapplo.Windows/blob/master/src/Dapplo.Windows.Shell32/Enums/AppBarMessages.cs)(=5) and a reference to an [AppBarData](https://github.com/dapplo/Dapplo.Windows/blob/master/src/Dapplo.Windows.Shell32/Structs/AppBarData.cs) struct. 

The DllImport
```
        /// <summary>
        /// Sends an appbar message to the system.
        /// See <a href="https://msdn.microsoft.com/en-us/library/windows/desktop/bb762108.aspx">SHAppBarMessage function</a>
        /// </summary>
        /// <param name="dwMessage">AppBarMessages - Appbar message value to send.</param>
        /// <param name="pData">A pointer to an AppBarData structure. The content of the structure on entry and on exit depends on the value set in the dwMessage parameter.
        /// See the individual message pages for specifics.</param>
        /// <returns></returns>
        [DllImport("shell32", SetLastError = true)]
        private static extern IntPtr SHAppBarMessage(AppBarMessages dwMessage, [In] ref AppBarData pData);
```

After having called this, you can use it to calculate the EjectDirection or the position.

If your NotificationsWindow is a top level window (no parent) you can add WinProc (see http://stackoverflow.com/a/1926796/1886251) to catch the WM_SETTINGCHANGE (0x001A or WM_WININICHANGE) [message](https://github.com/dapplo/Dapplo.Windows/blob/master/src/Dapplo.Windows.Messages/WindowsMessages.cs) and check if the "wParam" is SPI_SETWORKAREA (47). This than means the work-area (taskbar) has changed, so you will need to invoke the UpdateEjectDirectionRequested and UpdatePositionRequested event handlers.
(This is the code which is in my constructor does this more fancy.)

You could cache the AppBarData until the WM_SETTINGCHANGE  but I don't think it is needed.

**Comment by Lakritzator** [comment]
Another P.S.
There are technologies where your WindowPositionProvider could literally "follow" any window (not Window), also from processes you don't own. I have code which can help, but again... this also uses additional libraries (System.Reactive) to keep my code clean.

Ah before I forget, your project is very cool but it lacks comments :smile:

**Comment by raflop** [comment]
I will try to do something with comments xD

About additional PositionProviders which requires third party libraries like ReactiveExtensions, my plan is that they will come in separate nuget packages as a  plugins eg. "ToastNotifications.PositionProviders.ProviderName" 

Your idea is interesting if you would like share the code with me, I could add plugin like that

**Comment by Lakritzator** [comment]
I have no problems with sharing some stuff.

If you are going to have multiple projects, and nuget packages, I would advice you to get an [AppVeyor](https://www.appveyor.com/) account. With that you can automatically build and publish packages as soon as you push your changes. It should be free for open source.
I use this with all my nuget packages, it prevents viruses and having "none committed code" in the end product.

**Comment by raflop** [comment]
Thanks a lot !

**Comment by raflop** [comment]
Hi, I released new nuget package v 1.6.1 which contains changes for this issue.

**Comment by Lakritzator** [comment]
You mean 2.1.1, right? Thanks.
I will need to check this tomorrow at work, somehow I don't get it working at my private laptop. But I already downgraded and it still doesn't work. Must be something here... maybe Windows 10, I still work with Windows 7 at work 😢

**Comment by raflop** [comment]
yeah 2.1.1 :) (edited)

**Comment by Lakritzator** [comment]
With windows 7 it seems to work, I wonder if it ever worked on windows 10... Do you use windows 10??

**Comment by raflop** [comment]
Yes, every day :)

**Comment by Lakritzator** [comment]
Weird... I will need to check this during the weekend. I was in a bit of a hurry, so I probably did something completely wrong :)

Anyway, thanks for the feedback. I will let you know via a comment, but as the main issue is solved I will close this.

**Comment by Lakritzator** [comment]
So, what I found up to now is that your IPositionProvider returns virtual coordinates (DPI unaware) and mine real coordinates (DPI aware). Probably your displaying code is also DPI unaware and thus it works for your IPositionProvider. Now, in Windows 10 my DPI settings are at 125%, in Windows 7 they are not...

So, I need to figure out how to make things work together.

**Comment by raflop** [comment]
Hi, 

Just worth mentioning, there was a bug with positioning which I fixed in v 2.1.2 in Window Position Provider.

About DPI, I think that the built-in provides should work on different DPIs, because they just deal with WPF components and I guess WPF takes care about coordinates recalculating. But in your case you have to take DPI from system and recalculate coordinates using that DPI by yourself.

**Comment by Lakritzator** [comment]
FYI:
I tried the build-in position providers, but they cannot handle different taskbar placements.

So I got my SystemTrayPositionProvider working with the newest version, and as my application is fully DPI aware and ToastNotifications is "somehow" not (still need to figure out the details) I needed to scale / unscale the coordinates, it now works.

See: 
https://github.com/dapplo/Dapplo.CaliburnMicro/blob/master/src/Dapplo.CaliburnMicro.Toasts/SystemTrayPositionProvider.cs

Even if there are already notifications, they are moved to the correct location if the taskbar is relocated.

**Comment by rafallopatka** [comment]
Hi, It looks interesting. Is there possibility to share your code in this library or in a separated plugin using core of Dapplo example ToastNotifications.Dapplo.SystemTray ?

**Comment by Lakritzator** [comment]
The system-tray code on it's turn is using **multiple** Dapplo.Windows packages, and this becomes a mess. The code in Dapplo.CaliburnMicro.Toasts makes your ToastNotifications work with Caliburn.Micro (MVVM), but this doesn't work without the other packages...

Maybe I can extract all the needed code, but first I need to understand why your code doesn't calculate with the real screen coordinates, even if the application is set to be DPI aware! 😕

**Comment by Lakritzator** [comment]
In the mean time I managed to understand how ToastNotifications doesn't need to know the real screen values, I actually forgot that WPF doesn't care for screen pixels! So everything is based upon 96 dpi, and will be automatically scaled when drawn.

This is why when I call Windows 32 APIS to get coordinates on the screen, I need to calculate them back.
With this information, I will see if I can whip up a reduced version of my SystemTrayPositionProvider.
